### ISSUE TITLE
Scrolling as a result of tabbing makes visible the path, but not the title of the result

### ISSUE THREAD

**Issue by grahamperrin** [szupie/tab-focus-google#1]
At <https://www.google.com/search?client=firefox-b-d&q=%22ERROR-tried-to-rebuild-during-make-install%22> for example: 

![image](https://user-images.githubusercontent.com/192271/102006330-4e791680-3d18-11eb-8cb6-519b1de7d302.png)

**Comment by grahamperrin** [comment]
Comparable symptoms (maybe the same root cause) with [Google Tab Hotkey](https://addons.mozilla.org/addon/google-tab-hotkey/) at <https://www.google.com/search?q=%22ERROR-tried-to-rebuild-during-make-install%22&client=firefox-b-d&ei=vcjVX-HkBeS78gK9uov4Cg&start=10&sa=N&ved=2ahUKEwiht52yvcrtAhXknVwKHT3dAq8Q8tMDegQICxA1&biw=1440&bih=956>

![image](https://user-images.githubusercontent.com/192271/102006375-9b5ced00-3d18-11eb-9cad-2423ce1b29b9.png)

**Comment by szupie** [comment]
For what it’s worth, this is standard browser behaviour when tabbing through different elements on a page. The page will only scroll down until the next focused item sits on the bottom edge of the viewport – but in the case of Google’s results page, the selected URL status panel on the bottom left corner obstructs the selected title fully if it is too short.

But I do agree this is not the best behaviour, and it’s something that’s bugged me from the start. I’ll look for a way override this default behaviour. Ideally I think the description of each result should also be scrolled into view.

**Comment by grahamperrin** [comment]
Thanks; understood. 

I wondered whether there are suitable anchors; from use of [Display #Anchors](https://addons.mozilla.org/addon/display-_anchors/), I think not.

**Comment by szupie** [comment]
c4e554b288d4cff3a02616838a168878050686e0
Results now scroll completely into view on focus

This updated version is also live on [AMO](https://addons.mozilla.org/en-US/firefox/addon/tab-focus-google/), so your addon should update itself soon. Let me know if you run into any issues as you’re using this! Thanks!
